OBJS += techlibs/prism/prism/wire_map.o
OBJS += techlibs/prism/prism/decision_tree.o
OBJS += techlibs/prism/prism/parse_context.o
OBJS += techlibs/prism/prism/components.o
OBJS += techlibs/prism/prism/config.o
OBJS += techlibs/prism/prism/prism.o
OBJS += techlibs/prism/synth_prism.o
